export type Readiness = "possible" | "partielle" | "impossible";

export type Opportunity = {
  id: string;
  searchId: string;
  tenderId?: string;
  score: number;
  client: string;
  ref: string;
  object: string;
  title: string;
  budget: number;
  budgetLabel: string;
  deadline: string;
  deadlineLong: string;
  daysLeft: number;
  source: string;
  sourceLong: string;
  place: string;
  matches: string[];
  summary: string;
  documents: { label: string; ok: boolean }[];
  readiness: Readiness;
  readinessText: string;
  today: boolean;
  seen: boolean;
};

export const readinessMeta: Record<Readiness, { label: string; tone: "ok" | "warn" | "bad" }> = {
  possible: { label: "Possible", tone: "ok" },
  partielle: { label: "Partielle", tone: "warn" },
  impossible: { label: "Impossible actuellement", tone: "bad" },
};

export const ignoreReasons = [
  "Hors périmètre",
  "Budget insuffisant",
  "Produit non pertinent",
  "Délai trop court",
  "Doublon",
  "Autre",
];

const docsFull = [
  { label: "Avis d'appel d'offres", ok: true },
  { label: "Règlement de consultation", ok: true },
  { label: "Cahier des prescriptions spéciales", ok: true },
  { label: "Bordereau des prix", ok: true },
];

const docsPartial = [
  { label: "Avis d'appel d'offres", ok: true },
  { label: "Règlement de consultation", ok: true },
  { label: "Cahier des prescriptions spéciales", ok: false },
  { label: "Bordereau des prix", ok: false },
];

const docsNone = [
  { label: "Avis d'appel d'offres", ok: true },
  { label: "Règlement de consultation", ok: false },
  { label: "Cahier des prescriptions spéciales", ok: false },
  { label: "Bordereau des prix", ok: false },
];

export const opportunities: Opportunity[] = [
  {
    id: "o-onee",
    searchId: "r4",
    tenderId: "onee",
    score: 92,
    client: "ONEE – Branche Eau",
    ref: "24/DRC/CI/2026",
    object: "Débitmètres électromagnétiques",
    title: "Acquisition de débitmètres électromagnétiques",
    budget: 1200000,
    budgetLabel: "1 200 000 MAD TTC",
    deadline: "23 juil.",
    deadlineLong: "23 juillet 2026",
    daysLeft: 12,
    source: "Marchés Publics",
    sourceLong: "Portail des marchés publics",
    place: "Rabat / Casablanca-Settat",
    matches: [
      'Mot-clé « débitmètre »',
      'Famille « Instrumentation »',
      "Client correspondant aux cibles PROMAT",
      "Budget supérieur au seuil défini",
    ],
    summary:
      "Le marché concerne l'acquisition de débitmètres électromagnétiques destinés au secteur de production ONEE Settat – Berrechid – Benslimane.",
    documents: docsFull,
    readiness: "possible",
    readinessText: "Les documents nécessaires à une première analyse sont disponibles.",
    today: true,
    seen: false,
  },
  {
    id: "o-ocp",
    searchId: "r4",
    tenderId: "ocp",
    score: 84,
    client: "OCP Group",
    ref: "118/OCP/2026",
    object: "Vannes automatiques de régulation",
    title: "Fourniture de vannes automatiques de régulation",
    budget: 2450000,
    budgetLabel: "2 450 000 MAD TTC",
    deadline: "05 août",
    deadlineLong: "5 août 2026",
    daysLeft: 25,
    source: "OCP",
    sourceLong: "Portail achats OCP Group",
    place: "Jorf Lasfar / El Jadida",
    matches: [
      'Mot-clé « vanne de régulation »',
      'Famille « Instrumentation »',
      "Client correspondant aux cibles PROMAT",
      "Budget supérieur au seuil défini",
    ],
    summary:
      "Fourniture de vannes automatiques de régulation pour les lignes de traitement du site de Jorf Lasfar, avec mise en service assistée.",
    documents: docsPartial,
    readiness: "partielle",
    readinessText:
      "L'avis est disponible, mais certains documents du dossier doivent encore être récupérés.",
    today: true,
    seen: false,
  },
  {
    id: "o-oncf",
    searchId: "r4",
    tenderId: "oncf",
    score: 81,
    client: "ONCF",
    ref: "07/ONCF/MT/2026",
    object: "Capteurs de pression ferroviaires",
    title: "Acquisition de capteurs de pression pour matériel roulant",
    budget: 680000,
    budgetLabel: "680 000 MAD TTC",
    deadline: "12 août",
    deadlineLong: "12 août 2026",
    daysLeft: 32,
    source: "Marchés Publics",
    sourceLong: "Portail des marchés publics",
    place: "Casablanca / Rabat",
    matches: [
      'Mot-clé « capteur de pression »',
      'Famille « Instrumentation »',
      "Client correspondant aux cibles PROMAT",
      "Références PROMAT similaires disponibles",
    ],
    summary:
      "Acquisition de capteurs de pression destinés à la maintenance du matériel roulant des ateliers ONCF de Casablanca.",
    documents: docsFull,
    readiness: "possible",
    readinessText: "Les documents nécessaires à une première analyse sont disponibles.",
    today: false,
    seen: true,
  },
  {
    id: "o-oned",
    searchId: "r4",
    tenderId: undefined,
    score: 76,
    client: "Régie de Tanger (Amendis)",
    ref: "45/AMD/2026",
    object: "Transmetteurs de niveau",
    title: "Fourniture de transmetteurs de niveau et accessoires",
    budget: 340000,
    budgetLabel: "340 000 MAD TTC",
    deadline: "18 juil.",
    deadlineLong: "18 juillet 2026",
    daysLeft: 7,
    source: "Presse",
    sourceLong: "Annonce presse — dossier non publié en ligne",
    place: "Tanger-Tétouan-Al Hoceïma",
    matches: ['Mot-clé « transmetteur »', 'Famille « Instrumentation »'],
    summary:
      "Fourniture de transmetteurs de niveau pour les réservoirs de la zone nord. Le dossier complet n'est pas publié en ligne.",
    documents: docsNone,
    readiness: "impossible",
    readinessText: "Le dossier complet n'est pas accessible depuis la source.",
    today: true,
    seen: false,
  },

  {
    id: "o-marsa",
    searchId: "r3",
    tenderId: "marsa",
    score: 79,
    client: "Marsa Maroc",
    ref: "32/MM/TC/2026",
    object: "Groupes hydrauliques portuaires",
    title: "Acquisition de groupes hydrauliques pour portiques",
    budget: 1850000,
    budgetLabel: "1 850 000 MAD TTC",
    deadline: "29 juil.",
    deadlineLong: "29 juillet 2026",
    daysLeft: 18,
    source: "Marsa Maroc",
    sourceLong: "Portail fournisseurs Marsa Maroc",
    place: "Casablanca — Terminal à conteneurs",
    matches: [
      'Mot-clé « groupe hydraulique »',
      'Famille « Hydraulique »',
      "Client correspondant aux cibles PROMAT",
      "Budget supérieur au seuil défini",
    ],
    summary:
      "Acquisition de groupes hydrauliques destinés aux portiques du terminal à conteneurs de Casablanca, pièces d'origine exigées.",
    documents: docsFull,
    readiness: "possible",
    readinessText: "Les documents nécessaires à une première analyse sont disponibles.",
    today: true,
    seen: false,
  },
  {
    id: "o-hyd2",
    searchId: "r3",
    score: 74,
    client: "OCP Group",
    ref: "126/OCP/2026",
    object: "Vérins hydrauliques double effet",
    title: "Fourniture de vérins hydrauliques double effet",
    budget: 520000,
    budgetLabel: "520 000 MAD TTC",
    deadline: "02 août",
    deadlineLong: "2 août 2026",
    daysLeft: 22,
    source: "OCP",
    sourceLong: "Portail achats OCP Group",
    place: "Khouribga",
    matches: ['Mot-clé « vérin »', 'Famille « Hydraulique »', "Client cible PROMAT"],
    summary:
      "Fourniture de vérins hydrauliques double effet pour les convoyeurs de la plateforme de Khouribga.",
    documents: docsPartial,
    readiness: "partielle",
    readinessText:
      "L'avis est disponible, mais certains documents du dossier doivent encore être récupérés.",
    today: true,
    seen: false,
  },
  {
    id: "o-hyd3",
    searchId: "r3",
    score: 71,
    client: "ONEE – Branche Électricité",
    ref: "88/ONEE/EL/2026",
    object: "Pompes et flexibles hydrauliques",
    title: "Acquisition de pompes et flexibles hydrauliques",
    budget: 410000,
    budgetLabel: "410 000 MAD TTC",
    deadline: "27 juil.",
    deadlineLong: "27 juillet 2026",
    daysLeft: 16,
    source: "Marchés Publics",
    sourceLong: "Portail des marchés publics",
    place: "Mohammedia",
    matches: ['Mot-clé « pompe »', 'Famille « Hydraulique »'],
    summary:
      "Acquisition de pompes et de flexibles hydrauliques pour la centrale thermique de Mohammedia.",
    documents: docsFull,
    readiness: "possible",
    readinessText: "Les documents nécessaires à une première analyse sont disponibles.",
    today: false,
    seen: true,
  },
  {
    id: "o-hyd4",
    searchId: "r3",
    score: 66,
    client: "SOMAS",
    ref: "12/SOMAS/2026",
    object: "Centrale hydraulique mobile",
    title: "Acquisition d'une centrale hydraulique mobile",
    budget: 260000,
    budgetLabel: "260 000 MAD TTC",
    deadline: "31 juil.",
    deadlineLong: "31 juillet 2026",
    daysLeft: 20,
    source: "Presse",
    sourceLong: "Annonce presse",
    place: "Agadir",
    matches: ['Famille « Hydraulique »'],
    summary: "Acquisition d'une centrale hydraulique mobile pour l'atelier de maintenance d'Agadir.",
    documents: docsNone,
    readiness: "impossible",
    readinessText: "Le dossier complet n'est pas accessible depuis la source.",
    today: false,
    seen: false,
  },
  {
    id: "o-hyd5",
    searchId: "r3",
    score: 63,
    client: "Régie de Marrakech (RADEEMA)",
    ref: "56/RDM/2026",
    object: "Kits de joints hydrauliques",
    title: "Fourniture de kits de joints hydrauliques",
    budget: 95000,
    budgetLabel: "95 000 MAD TTC",
    deadline: "16 juil.",
    deadlineLong: "16 juillet 2026",
    daysLeft: 5,
    source: "Marchés Publics",
    sourceLong: "Portail des marchés publics",
    place: "Marrakech",
    matches: ['Mot-clé « flexible »'],
    summary: "Fourniture de kits de joints et flexibles pour les stations de pompage de Marrakech.",
    documents: docsPartial,
    readiness: "partielle",
    readinessText:
      "L'avis est disponible, mais certains documents du dossier doivent encore être récupérés.",
    today: true,
    seen: false,
  },

  {
    id: "o-pdr1",
    searchId: "r1",
    score: 90,
    client: "Marsa Maroc",
    ref: "41/MM/PR/2026",
    object: "Pièces de rechange grues Grove",
    title: "Fourniture de pièces de rechange d'origine pour grues Grove",
    budget: 1450000,
    budgetLabel: "1 450 000 MAD TTC",
    deadline: "24 juil.",
    deadlineLong: "24 juillet 2026",
    daysLeft: 13,
    source: "Marsa Maroc",
    sourceLong: "Portail fournisseurs Marsa Maroc",
    place: "Casablanca",
    matches: [
      'Mot-clé « pièces détachées »',
      "Marque Grove suivie par PROMAT",
      "Client cible PROMAT",
      "Budget supérieur au seuil défini",
    ],
    summary:
      "Fourniture de pièces de rechange d'origine pour la flotte de grues mobiles Grove du port de Casablanca.",
    documents: docsFull,
    readiness: "possible",
    readinessText: "Les documents nécessaires à une première analyse sont disponibles.",
    today: true,
    seen: false,
  },
  {
    id: "o-pdr2",
    searchId: "r1",
    score: 87,
    client: "ONCF",
    ref: "19/ONCF/PR/2026",
    object: "Pièces de rechange engins de voie Terex",
    title: "Acquisition de pièces de rechange pour engins de voie Terex",
    budget: 980000,
    budgetLabel: "980 000 MAD TTC",
    deadline: "07 août",
    deadlineLong: "7 août 2026",
    daysLeft: 27,
    source: "Marchés Publics",
    sourceLong: "Portail des marchés publics",
    place: "Fès / Meknès",
    matches: ['Mot-clé « Terex »', "Client cible PROMAT", "Références PROMAT similaires"],
    summary:
      "Acquisition de pièces de rechange pour les engins de voie Terex des ateliers ONCF de Fès.",
    documents: docsFull,
    readiness: "possible",
    readinessText: "Les documents nécessaires à une première analyse sont disponibles.",
    today: true,
    seen: false,
  },
  {
    id: "o-pdr3",
    searchId: "r1",
    score: 82,
    client: "OCP Group",
    ref: "131/OCP/2026",
    object: "Pièces de rechange Potain",
    title: "Fourniture de pièces de rechange pour grues à tour Potain",
    budget: 720000,
    budgetLabel: "720 000 MAD TTC",
    deadline: "11 août",
    deadlineLong: "11 août 2026",
    daysLeft: 31,
    source: "OCP",
    sourceLong: "Portail achats OCP Group",
    place: "Safi",
    matches: ['Mot-clé « Potain »', "Client cible PROMAT"],
    summary: "Fourniture de pièces de rechange pour les grues à tour Potain du site de Safi.",
    documents: docsPartial,
    readiness: "partielle",
    readinessText:
      "L'avis est disponible, mais certains documents du dossier doivent encore être récupérés.",
    today: false,
    seen: true,
  },
  {
    id: "o-pdr4",
    searchId: "r1",
    score: 78,
    client: "ONEE – Branche Eau",
    ref: "31/DRC/PR/2026",
    object: "Pièces détachées pompes doseuses",
    title: "Fourniture de pièces détachées pour pompes doseuses",
    budget: 380000,
    budgetLabel: "380 000 MAD TTC",
    deadline: "21 juil.",
    deadlineLong: "21 juillet 2026",
    daysLeft: 10,
    source: "Marchés Publics",
    sourceLong: "Portail des marchés publics",
    place: "Kénitra",
    matches: ['Mot-clé « pièces détachées »', "Client cible PROMAT"],
    summary:
      "Fourniture de pièces détachées pour les pompes doseuses des stations de traitement de Kénitra.",
    documents: docsFull,
    readiness: "possible",
    readinessText: "Les documents nécessaires à une première analyse sont disponibles.",
    today: true,
    seen: false,
  },
  {
    id: "o-pdr5",
    searchId: "r1",
    score: 73,
    client: "Somaca",
    ref: "07/SMC/2026",
    object: "Pièces de rechange chariots élévateurs",
    title: "Fourniture de pièces de rechange pour chariots élévateurs",
    budget: 210000,
    budgetLabel: "210 000 MAD TTC",
    deadline: "19 juil.",
    deadlineLong: "19 juillet 2026",
    daysLeft: 8,
    source: "Privé",
    sourceLong: "Appel d'offres privé — dossier sur demande",
    place: "Casablanca",
    matches: ['Mot-clé « pièces détachées »'],
    summary:
      "Fourniture de pièces de rechange pour la flotte de chariots élévateurs de l'usine de Casablanca.",
    documents: docsPartial,
    readiness: "partielle",
    readinessText:
      "L'avis est disponible, mais certains documents du dossier doivent encore être récupérés.",
    today: false,
    seen: false,
  },
  {
    id: "o-pdr6",
    searchId: "r1",
    score: 70,
    client: "Régie de Tanger (Amendis)",
    ref: "52/AMD/2026",
    object: "Pièces de rechange groupes électrogènes",
    title: "Fourniture de pièces de rechange pour groupes électrogènes",
    budget: 165000,
    budgetLabel: "165 000 MAD TTC",
    deadline: "28 juil.",
    deadlineLong: "28 juillet 2026",
    daysLeft: 17,
    source: "Marchés Publics",
    sourceLong: "Portail des marchés publics",
    place: "Tanger",
    matches: ['Mot-clé « pièces détachées »'],
    summary:
      "Fourniture de pièces de rechange pour les groupes électrogènes des stations de relevage de Tanger.",
    documents: docsFull,
    readiness: "possible",
    readinessText: "Les documents nécessaires à une première analyse sont disponibles.",
    today: false,
    seen: false,
  },
  {
    id: "o-pdr7",
    searchId: "r1",
    score: 68,
    client: "Ciments du Maroc",
    ref: "22/CDM/2026",
    object: "Pièces d'usure concasseurs",
    title: "Fourniture de pièces d'usure pour concasseurs",
    budget: 640000,
    budgetLabel: "640 000 MAD TTC",
    deadline: "14 août",
    deadlineLong: "14 août 2026",
    daysLeft: 34,
    source: "Privé",
    sourceLong: "Appel d'offres privé",
    place: "Safi",
    matches: ['Famille « Pièces de rechange »'],
    summary: "Fourniture de pièces d'usure pour les concasseurs de la cimenterie de Safi.",
    documents: docsNone,
    readiness: "impossible",
    readinessText: "Le dossier complet n'est pas accessible depuis la source.",
    today: true,
    seen: false,
  },
  {
    id: "o-pdr8",
    searchId: "r1",
    score: 64,
    client: "Port de Nador",
    ref: "09/PN/2026",
    object: "Pièces de rechange treuils",
    title: "Fourniture de pièces de rechange pour treuils de quai",
    budget: 120000,
    budgetLabel: "120 000 MAD TTC",
    deadline: "17 juil.",
    deadlineLong: "17 juillet 2026",
    daysLeft: 6,
    source: "Marchés Publics",
    sourceLong: "Portail des marchés publics",
    place: "Nador",
    matches: ['Mot-clé « treuil »'],
    summary: "Fourniture de pièces de rechange pour les treuils de quai du port de Nador.",
    documents: docsPartial,
    readiness: "partielle",
    readinessText:
      "L'avis est disponible, mais certains documents du dossier doivent encore être récupérés.",
    today: true,
    seen: true,
  },

  {
    id: "o-lev1",
    searchId: "r2",
    score: 88,
    client: "Marsa Maroc",
    ref: "37/MM/LV/2026",
    object: "Palans électriques et treuils",
    title: "Fourniture de palans électriques et treuils de manutention",
    budget: 890000,
    budgetLabel: "890 000 MAD TTC",
    deadline: "26 juil.",
    deadlineLong: "26 juillet 2026",
    daysLeft: 15,
    source: "Marsa Maroc",
    sourceLong: "Portail fournisseurs Marsa Maroc",
    place: "Agadir",
    matches: ['Mot-clé « palan »', 'Famille « Levage »', "Client cible PROMAT"],
    summary:
      "Fourniture de palans électriques et treuils pour les opérations de manutention portuaire d'Agadir.",
    documents: docsFull,
    readiness: "possible",
    readinessText: "Les documents nécessaires à une première analyse sont disponibles.",
    today: false,
    seen: false,
  },
  {
    id: "o-lev2",
    searchId: "r2",
    score: 75,
    client: "ONCF",
    ref: "23/ONCF/LV/2026",
    object: "Grue d'atelier 20 t",
    title: "Acquisition d'une grue d'atelier de 20 tonnes",
    budget: 1650000,
    budgetLabel: "1 650 000 MAD TTC",
    deadline: "09 août",
    deadlineLong: "9 août 2026",
    daysLeft: 29,
    source: "Marchés Publics",
    sourceLong: "Portail des marchés publics",
    place: "Casablanca",
    matches: ['Mot-clé « grue »', 'Famille « Levage »', "Budget supérieur au seuil défini"],
    summary: "Acquisition d'une grue d'atelier de 20 tonnes pour le dépôt ONCF de Casablanca.",
    documents: docsPartial,
    readiness: "partielle",
    readinessText:
      "L'avis est disponible, mais certains documents du dossier doivent encore être récupérés.",
    today: false,
    seen: true,
  },
  {
    id: "o-lev3",
    searchId: "r2",
    score: 69,
    client: "Zone franche Kénitra",
    ref: "15/ZFK/2026",
    object: "Ponts roulants",
    title: "Fourniture et montage de ponts roulants",
    budget: 2100000,
    budgetLabel: "2 100 000 MAD TTC",
    deadline: "13 août",
    deadlineLong: "13 août 2026",
    daysLeft: 33,
    source: "Privé",
    sourceLong: "Appel d'offres privé",
    place: "Kénitra",
    matches: ['Famille « Levage »', "Budget supérieur au seuil défini"],
    summary:
      "Fourniture et montage de ponts roulants pour un nouvel atelier de la zone franche de Kénitra.",
    documents: docsNone,
    readiness: "impossible",
    readinessText: "Le dossier complet n'est pas accessible depuis la source.",
    today: false,
    seen: false,
  },

  {
    id: "o-ind1",
    searchId: "r5",
    score: 80,
    client: "ONEE – Branche Électricité",
    ref: "94/ONEE/EL/2026",
    object: "Compresseurs d'air industriels",
    title: "Acquisition de compresseurs d'air industriels",
    budget: 1300000,
    budgetLabel: "1 300 000 MAD TTC",
    deadline: "30 juil.",
    deadlineLong: "30 juillet 2026",
    daysLeft: 19,
    source: "Marchés Publics",
    sourceLong: "Portail des marchés publics",
    place: "Jerada",
    matches: ['Mot-clé « compresseur »', "Client cible PROMAT", "Budget supérieur au seuil défini"],
    summary:
      "Acquisition de compresseurs d'air industriels pour la centrale de Jerada, montage et mise en service inclus.",
    documents: docsFull,
    readiness: "possible",
    readinessText: "Les documents nécessaires à une première analyse sont disponibles.",
    today: false,
    seen: false,
  },
  {
    id: "o-ind2",
    searchId: "r5",
    score: 67,
    client: "OCP Group",
    ref: "140/OCP/2026",
    object: "Réducteurs industriels",
    title: "Fourniture de réducteurs industriels",
    budget: 470000,
    budgetLabel: "470 000 MAD TTC",
    deadline: "20 juil.",
    deadlineLong: "20 juillet 2026",
    daysLeft: 9,
    source: "OCP",
    sourceLong: "Portail achats OCP Group",
    place: "Benguerir",
    matches: ['Mot-clé « réducteur »', "Client cible PROMAT"],
    summary: "Fourniture de réducteurs industriels pour les convoyeurs du site de Benguerir.",
    documents: docsPartial,
    readiness: "partielle",
    readinessText:
      "L'avis est disponible, mais certains documents du dossier doivent encore être récupérés.",
    today: false,
    seen: true,
  },
];
