/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccueilRouteImport } from './routes/accueil'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as ArticlesBesoinsRouteImport } from './routes/articles-besoins'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as OffresFinalesRouteImport } from './routes/offres-finales'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as RecherchesRouteImport } from './routes/recherches'
import { Route as AppelsOffresIndexRouteImport } from './routes/appels-offres.index'
import { Route as AppelsOffresIdRouteImport } from './routes/appels-offres.$id'
import { Route as ChiffragesIndexRouteImport } from './routes/chiffrages.index'
import { Route as ChiffragesIdRouteImport } from './routes/chiffrages.$id'
import { Route as FournisseursIndexRouteImport } from './routes/fournisseurs.index'
import { Route as FournisseursIdRouteImport } from './routes/fournisseurs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccueilRoute = AccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesBesoinsRoute = ArticlesBesoinsRouteImport.update({
  id: '/articles-besoins',
  path: '/articles-besoins',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresFinalesRoute = OffresFinalesRouteImport.update({
  id: '/offres-finales',
  path: '/offres-finales',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const RecherchesRoute = RecherchesRouteImport.update({
  id: '/recherches',
  path: '/recherches',
  getParentRoute: () => rootRouteImport,
} as any)
const AppelsOffresIndexRoute = AppelsOffresIndexRouteImport.update({
  id: '/appels-offres/',
  path: '/appels-offres/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppelsOffresIdRoute = AppelsOffresIdRouteImport.update({
  id: '/appels-offres/$id',
  path: '/appels-offres/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiffragesIndexRoute = ChiffragesIndexRouteImport.update({
  id: '/chiffrages/',
  path: '/chiffrages/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiffragesIdRoute = ChiffragesIdRouteImport.update({
  id: '/chiffrages/$id',
  path: '/chiffrages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursIndexRoute = FournisseursIndexRouteImport.update({
  id: '/fournisseurs/',
  path: '/fournisseurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const FournisseursIdRoute = FournisseursIdRouteImport.update({
  id: '/fournisseurs/$id',
  path: '/fournisseurs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/analyses': typeof AnalysesRoute
  '/articles-besoins': typeof ArticlesBesoinsRoute
  '/consultations': typeof ConsultationsRoute
  '/historique': typeof HistoriqueRoute
  '/offres-finales': typeof OffresFinalesRoute
  '/parametres': typeof ParametresRoute
  '/recherches': typeof RecherchesRoute
  '/appels-offres/$id': typeof AppelsOffresIdRoute
  '/chiffrages/$id': typeof ChiffragesIdRoute
  '/fournisseurs/$id': typeof FournisseursIdRoute
  '/appels-offres/': typeof AppelsOffresIndexRoute
  '/chiffrages/': typeof ChiffragesIndexRoute
  '/fournisseurs/': typeof FournisseursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/analyses': typeof AnalysesRoute
  '/articles-besoins': typeof ArticlesBesoinsRoute
  '/consultations': typeof ConsultationsRoute
  '/historique': typeof HistoriqueRoute
  '/offres-finales': typeof OffresFinalesRoute
  '/parametres': typeof ParametresRoute
  '/recherches': typeof RecherchesRoute
  '/appels-offres/$id': typeof AppelsOffresIdRoute
  '/chiffrages/$id': typeof ChiffragesIdRoute
  '/fournisseurs/$id': typeof FournisseursIdRoute
  '/appels-offres': typeof AppelsOffresIndexRoute
  '/chiffrages': typeof ChiffragesIndexRoute
  '/fournisseurs': typeof FournisseursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accueil': typeof AccueilRoute
  '/analyses': typeof AnalysesRoute
  '/articles-besoins': typeof ArticlesBesoinsRoute
  '/consultations': typeof ConsultationsRoute
  '/historique': typeof HistoriqueRoute
  '/offres-finales': typeof OffresFinalesRoute
  '/parametres': typeof ParametresRoute
  '/recherches': typeof RecherchesRoute
  '/appels-offres/$id': typeof AppelsOffresIdRoute
  '/chiffrages/$id': typeof ChiffragesIdRoute
  '/fournisseurs/$id': typeof FournisseursIdRoute
  '/appels-offres/': typeof AppelsOffresIndexRoute
  '/chiffrages/': typeof ChiffragesIndexRoute
  '/fournisseurs/': typeof FournisseursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accueil'
    | '/analyses'
    | '/articles-besoins'
    | '/consultations'
    | '/historique'
    | '/offres-finales'
    | '/parametres'
    | '/recherches'
    | '/appels-offres/$id'
    | '/chiffrages/$id'
    | '/fournisseurs/$id'
    | '/appels-offres/'
    | '/chiffrages/'
    | '/fournisseurs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accueil'
    | '/analyses'
    | '/articles-besoins'
    | '/consultations'
    | '/historique'
    | '/offres-finales'
    | '/parametres'
    | '/recherches'
    | '/appels-offres/$id'
    | '/chiffrages/$id'
    | '/fournisseurs/$id'
    | '/appels-offres'
    | '/chiffrages'
    | '/fournisseurs'
  id:
    | '__root__'
    | '/'
    | '/accueil'
    | '/analyses'
    | '/articles-besoins'
    | '/consultations'
    | '/historique'
    | '/offres-finales'
    | '/parametres'
    | '/recherches'
    | '/appels-offres/$id'
    | '/chiffrages/$id'
    | '/fournisseurs/$id'
    | '/appels-offres/'
    | '/chiffrages/'
    | '/fournisseurs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccueilRoute: typeof AccueilRoute
  AnalysesRoute: typeof AnalysesRoute
  ArticlesBesoinsRoute: typeof ArticlesBesoinsRoute
  ConsultationsRoute: typeof ConsultationsRoute
  HistoriqueRoute: typeof HistoriqueRoute
  OffresFinalesRoute: typeof OffresFinalesRoute
  ParametresRoute: typeof ParametresRoute
  RecherchesRoute: typeof RecherchesRoute
  AppelsOffresIdRoute: typeof AppelsOffresIdRoute
  ChiffragesIdRoute: typeof ChiffragesIdRoute
  FournisseursIdRoute: typeof FournisseursIdRoute
  AppelsOffresIndexRoute: typeof AppelsOffresIndexRoute
  ChiffragesIndexRoute: typeof ChiffragesIndexRoute
  FournisseursIndexRoute: typeof FournisseursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accueil': {
      id: '/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AccueilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles-besoins': {
      id: '/articles-besoins'
      path: '/articles-besoins'
      fullPath: '/articles-besoins'
      preLoaderRoute: typeof ArticlesBesoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres-finales': {
      id: '/offres-finales'
      path: '/offres-finales'
      fullPath: '/offres-finales'
      preLoaderRoute: typeof OffresFinalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherches': {
      id: '/recherches'
      path: '/recherches'
      fullPath: '/recherches'
      preLoaderRoute: typeof RecherchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appels-offres/': {
      id: '/appels-offres/'
      path: '/appels-offres'
      fullPath: '/appels-offres/'
      preLoaderRoute: typeof AppelsOffresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appels-offres/$id': {
      id: '/appels-offres/$id'
      path: '/appels-offres/$id'
      fullPath: '/appels-offres/$id'
      preLoaderRoute: typeof AppelsOffresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chiffrages/': {
      id: '/chiffrages/'
      path: '/chiffrages'
      fullPath: '/chiffrages/'
      preLoaderRoute: typeof ChiffragesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chiffrages/$id': {
      id: '/chiffrages/$id'
      path: '/chiffrages/$id'
      fullPath: '/chiffrages/$id'
      preLoaderRoute: typeof ChiffragesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs/': {
      id: '/fournisseurs/'
      path: '/fournisseurs'
      fullPath: '/fournisseurs/'
      preLoaderRoute: typeof FournisseursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fournisseurs/$id': {
      id: '/fournisseurs/$id'
      path: '/fournisseurs/$id'
      fullPath: '/fournisseurs/$id'
      preLoaderRoute: typeof FournisseursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccueilRoute: AccueilRoute,
  AnalysesRoute: AnalysesRoute,
  ArticlesBesoinsRoute: ArticlesBesoinsRoute,
  ConsultationsRoute: ConsultationsRoute,
  HistoriqueRoute: HistoriqueRoute,
  OffresFinalesRoute: OffresFinalesRoute,
  ParametresRoute: ParametresRoute,
  RecherchesRoute: RecherchesRoute,
  AppelsOffresIdRoute: AppelsOffresIdRoute,
  ChiffragesIdRoute: ChiffragesIdRoute,
  FournisseursIdRoute: FournisseursIdRoute,
  AppelsOffresIndexRoute: AppelsOffresIndexRoute,
  ChiffragesIndexRoute: ChiffragesIndexRoute,
  FournisseursIndexRoute: FournisseursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
